version: '3'

networks:
  app-tier: # Main bridge network for application, NGINX & DB
    driver: bridge
    

services: 
  main:
    build: 
      context: .
      dockerfile: ./services/application/Dockerfile
      
    ports:  
    - "5000:5000"

    networks:
      - app-tier
  
  nginx:
    build: ./services/nginx
    ports:
    - "80:80"
        
    networks:
      - app-tier